"""empty message

Revision ID: 23360e2e8b26
Revises: a5e49b48582a
Create Date: 2021-01-01 22:47:41.570218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23360e2e8b26'
down_revision = 'a5e49b48582a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('botanas', 'cantidad')
    op.drop_column('enlatados', 'cantidad')
    op.drop_column('frutas', 'cantidad')
    op.drop_column('licores', 'cantidad')
    op.drop_column('refrescos', 'cantidad')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refrescos', sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('licores', sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('frutas', sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('enlatados', sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('botanas', sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
