"""empty message

Revision ID: 50242fb9bd77
Revises: 
Create Date: 2020-12-23 22:34:02.003468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50242fb9bd77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('apellido', sa.String(length=255), nullable=True),
    sa.Column('correo', sa.String(length=255), nullable=True),
    sa.Column('usuario', sa.String(length=255), nullable=True),
    sa.Column('contrasenia', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    # ### end Alembic commands ###
