"""empty message

Revision ID: 5c9dd9c76ff5
Revises: 31104bd9c96d
Create Date: 2021-01-04 20:54:11.063490

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5c9dd9c76ff5'
down_revision = '31104bd9c96d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listado', sa.Column('cliente_id', sa.Integer(), nullable=True))
    op.add_column('listado', sa.Column('costo_', sa.Float(), nullable=True))
    op.add_column('listado', sa.Column('nombre_cliente', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'listado', 'usuario', ['cliente_id'], ['id'])
    op.drop_column('listado', 'costo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listado', sa.Column('costo', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'listado', type_='foreignkey')
    op.drop_column('listado', 'nombre_cliente')
    op.drop_column('listado', 'costo_')
    op.drop_column('listado', 'cliente_id')
    # ### end Alembic commands ###
