"""empty message

Revision ID: 957df2383b3b
Revises: 
Create Date: 2021-03-31 20:01:36.841444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '957df2383b3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administracion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('apellido', sa.String(length=255), nullable=True),
    sa.Column('correo', sa.String(length=255), nullable=True),
    sa.Column('usuario', sa.String(length=255), nullable=True),
    sa.Column('contrasenia', sa.String(length=255), nullable=True),
    sa.Column('hora_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('apellido', sa.String(length=255), nullable=True),
    sa.Column('correo', sa.String(length=255), nullable=True),
    sa.Column('usuario', sa.String(length=255), nullable=True),
    sa.Column('contrasenia', sa.String(length=255), nullable=True),
    sa.Column('hora_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario__repatidor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('apellido', sa.String(length=255), nullable=True),
    sa.Column('correo', sa.String(length=255), nullable=True),
    sa.Column('usuario', sa.String(length=255), nullable=True),
    sa.Column('contrasenia', sa.String(length=255), nullable=True),
    sa.Column('hora_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('botanas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('costo', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enlatados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('costo', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('hora_Salida', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('frutas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('costo', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('licores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('costo', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refrescos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('costo', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('nombre_cliente', sa.String(length=255), nullable=True),
    sa.Column('frutas_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('cantidad', sa.String(length=255), nullable=True),
    sa.Column('costo', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['frutas_id'], ['frutas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listado')
    op.drop_table('refrescos')
    op.drop_table('licores')
    op.drop_table('frutas')
    op.drop_table('evaluacion')
    op.drop_table('enlatados')
    op.drop_table('botanas')
    op.drop_table('usuario__repatidor')
    op.drop_table('usuario')
    op.drop_table('producto')
    op.drop_table('administracion')
    # ### end Alembic commands ###
