"""empty message

Revision ID: 977564b82cb7
Revises: 0b6a73403b32
Create Date: 2021-01-01 22:17:54.158718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '977564b82cb7'
down_revision = '0b6a73403b32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('producto')
    # ### end Alembic commands ###
