"""empty message

Revision ID: ab10226e7f90
Revises: ab82e0d1146d
Create Date: 2021-01-10 14:23:40.830666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab10226e7f90'
down_revision = 'ab82e0d1146d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario__repatidor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('apellido', sa.String(length=255), nullable=True),
    sa.Column('correo', sa.String(length=255), nullable=True),
    sa.Column('usuario', sa.String(length=255), nullable=True),
    sa.Column('contrasenia', sa.String(length=255), nullable=True),
    sa.Column('hora_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario__repatidor')
    # ### end Alembic commands ###
