"""empty message

Revision ID: ab82e0d1146d
Revises: 5c9dd9c76ff5
Create Date: 2021-01-04 21:16:31.688803

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ab82e0d1146d'
down_revision = '5c9dd9c76ff5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listado', sa.Column('costo', sa.Float(), nullable=True))
    op.drop_column('listado', 'costo_')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listado', sa.Column('costo_', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('listado', 'costo')
    # ### end Alembic commands ###
